#!/usr/bin/env node
const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const js = fs.readFileSync(path.join(root, 'src', 'main.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles', 'main.css'), 'utf8');

function extractFunction(name) {
  const marker = `function ${name}(`;
  const start = js.indexOf(marker);
  assert(start !== -1, `${name} function exists`);
  let depth = 0;
  const bodyStart = js.indexOf('{', start);
  assert(bodyStart !== -1, `${name} function has body`);
  for (let i = bodyStart; i < js.length; i++) {
    if (js[i] === '{') depth++;
    if (js[i] === '}') depth--;
    if (depth === 0) return js.slice(start, i + 1);
  }
  throw new Error(`${name} function body did not close`);
}

const previewHihat = extractFunction('previewHihat');
assert(/initAudio\(\)/.test(previewHihat), 'previewHihat initializes/resumes audio before auditioning');
assert(/A\.currentTime\s*\+\s*\.0?\d+/.test(previewHihat), 'previewHihat schedules at a tiny currentTime offset');
assert(/synthHihat\s*\(/.test(previewHihat), 'previewHihat auditions the real synthHihat voice');
assert(/triggerCompGate\s*\(\s*t\s*,\s*tr\.id\s*\)/.test(previewHihat), 'previewHihat opens the compressor gate for hihat audition');
assert(previewHihat.indexOf('triggerCompGate') > -1 && previewHihat.indexOf('triggerCompGate') < previewHihat.indexOf('synthHihat'), 'previewHihat triggers compressor gate before synthHihat');
assert(/TRACKS\[2\]/.test(previewHihat), 'previewHihat uses current HHT track routing/volume from the hihat track');
assert(/(?:Object\.assign\s*\(\s*\{\s*\}\s*,\s*tr\.p\s*,\s*\{\s*open\s*:|\{\s*\.\.\.\s*tr\.p\s*,\s*open\s*:)/.test(previewHihat), 'previewHihat copies current hihat params and overrides only open for the preview');
assert(!/TRACKS\[2\]\.p\.open\s*=/.test(previewHihat), 'previewHihat must not mutate TRACKS[2].p.open');
assert(!/S\.playing\s*=/.test(previewHihat), 'previewHihat must not mutate transport playing state');
assert(!/\b(?:play|runSch)\s*\(/.test(previewHihat), 'previewHihat must not start the transport/scheduler');

const buildVE = extractFunction('buildVE');
assert(/tr\.id\s*===\s*['"]hihat['"]/.test(buildVE), 'buildVE has a HHT-only branch');
assert(/HAT TEST/.test(buildVE), 'buildVE renders a HAT TEST audition strip');
['CLOSED', 'TIGHT', 'OPEN'].forEach(label => {
  assert(buildVE.includes(label), `buildVE includes ${label} hihat preview button`);
});
assert(/previewHihat\(\s*0\s*\)/.test(buildVE), 'CLOSED button previews closed hihat open=0');
assert(/previewHihat\(\s*\.45\s*\)|previewHihat\(\s*0\.45\s*\)/.test(buildVE), 'TIGHT button previews partly-open hihat open≈0.45');
assert(/previewHihat\(\s*1\s*\)/.test(buildVE), 'OPEN button previews open hihat open=1');
assert(buildVE.indexOf('HAT TEST') > -1 && buildVE.indexOf('HAT TEST') < buildVE.indexOf("mkRow('FREQ'"), 'HAT TEST strip appears before HHT FREQ/DECAY/OPEN/METAL sliders');
assert(!html.includes('HAT TEST') && !html.includes('CLOSED') && !html.includes('TIGHT'), 'audition strip is generated by buildVE, not hard-coded in index.html');
assert(/hat-test/.test(css) && /min-height\s*:\s*(?:3[6-9]|[4-9]\d)px/.test(css), 'hihat audition strip has mobile thumb-friendly button styling');

console.log('Issue 003 hihat audition strip checks passed.');
