#!/usr/bin/env node
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const patternsModule = require(path.join(root, 'src', 'state', 'patterns.js'));
const ops = require(path.join(root, 'src', 'state', 'pattern-operations.js'));
const { createAppState } = require(path.join(root, 'src', 'state', 'app-state.js'));
const { createDefaultTracks } = require(path.join(root, 'src', 'state', 'tracks.js'));
const { createDefaultFxState } = require(path.join(root, 'src', 'state', 'fx-state.js'));
const { serializeProject, parseProjectImport } = require(path.join(root, 'src', 'state', 'persistence.js'));

const trackIds = ['kick', 'snare', 'hihat', 'clap', 'input', 'ether', 'synth'];
const { createDefaultRatchetGrid, createRatchetBanks, cloneRatchetGrid } = patternsModule;
const { getRatchetCount, setRatchetCount, cycleRatchetCount } = ops;
assert.strictEqual(typeof createDefaultRatchetGrid, 'function');
assert.strictEqual(typeof createRatchetBanks, 'function');
assert.strictEqual(typeof cloneRatchetGrid, 'function');
const grid = createDefaultRatchetGrid();
assert.deepStrictEqual(Object.keys(grid), trackIds);
trackIds.forEach(id => assert.deepStrictEqual(grid[id], Array(16).fill(1)));
grid.kick[0] = 3;
assert.strictEqual(createDefaultRatchetGrid().kick[0], 1, 'fresh default ratchet arrays');
const banks = createRatchetBanks();
assert.strictEqual(banks.length, 4);
banks[0].kick[0] = 2;
assert.strictEqual(banks[1].kick[0], 1, 'banks are independent');
const cloned = cloneRatchetGrid(banks[0]);
assert.deepStrictEqual(cloned, banks[0]);
assert.notStrictEqual(cloned, banks[0]);
assert.notStrictEqual(cloned.kick, banks[0].kick);
cloned.kick[0] = 3;
assert.strictEqual(banks[0].kick[0], 2);
assert.strictEqual(cloneRatchetGrid({ kick: [3] }).kick[1], 1, 'missing ratchet steps default to 1');
assert.strictEqual(cloneRatchetGrid({ kick: [3] }).snare[0], 1, 'missing ratchet tracks default to 1');
let r = createDefaultRatchetGrid();
assert.strictEqual(getRatchetCount(r, 'kick', 0), 1);
r = setRatchetCount(r, 'kick', 0, 2);
assert.strictEqual(getRatchetCount(r, 'kick', 0), 2);
r = cycleRatchetCount(r, 'kick', 0);
assert.strictEqual(getRatchetCount(r, 'kick', 0), 3);
r = cycleRatchetCount(r, 'kick', 0);
assert.strictEqual(getRatchetCount(r, 'kick', 0), 1);
r = cycleRatchetCount(r, 'kick', 0);
assert.strictEqual(getRatchetCount(r, 'kick', 0), 2);
[0, 4, 2.5, '2', NaN].forEach(count => assert.throws(() => setRatchetCount(r, 'kick', 0, count), /ratchet|count|1.*2.*3/i));
assert.throws(() => setRatchetCount(r, 'rim', 0, 2), /unknown track/i);
assert.throws(() => setRatchetCount(r, 'kick', 16, 2), /step/i);
let pattern = ops.createEmptyGrid();
r = setRatchetCount(createDefaultRatchetGrid(), 'kick', 4, 3);
let t = ops.toggleStep(pattern, 'kick', 4, r);
assert.strictEqual(t.pattern.kick[4], 1);
assert.strictEqual(t.ratchets.kick[4], 3, 'toggling on preserves stored ratchet');
t = ops.toggleStep(t.pattern, 'kick', 4, t.ratchets);
assert.strictEqual(t.pattern.kick[4], 0);
assert.strictEqual(t.ratchets.kick[4], 1, 'toggling off resets ratchet');
const c = ops.clearPattern(pattern, r);
assert.deepStrictEqual(c.pattern, ops.createEmptyGrid());
assert.deepStrictEqual(c.ratchets, createDefaultRatchetGrid());

const appState = createAppState();
const tracks = createDefaultTracks();
const fx = createDefaultFxState();
const patterns = patternsModule.createPatternBanks();
const ratchetBanks = createRatchetBanks();
ratchetBanks[2].hihat[7] = 3;
ratchetBanks[0].kick[0] = 2;
const serialized = serializeProject({ appState, tracks, fx, patterns, ratchets: ratchetBanks });
assert.deepStrictEqual(serialized.ratchets, ratchetBanks, 'serialize includes ratchets');
serialized.ratchets[0].kick[0] = 1;
assert.strictEqual(ratchetBanks[0].kick[0], 2, 'serialize clones ratchets');
const roundTrip = parseProjectImport(serializeProject({ appState, tracks, fx, patterns, ratchets: ratchetBanks }));
assert.strictEqual(roundTrip.ok, true);
assert.strictEqual(roundTrip.value.ratchets[2].hihat[7], 3, 'import round-trips ratchets');
const legacy = serializeProject({ appState, tracks, fx, patterns });
assert.strictEqual(Object.prototype.hasOwnProperty.call(legacy, 'ratchets'), false);
const legacyParsed = parseProjectImport(legacy);
assert.strictEqual(legacyParsed.ok, true);
assert.deepStrictEqual(legacyParsed.value.ratchets, createRatchetBanks(), 'legacy import hydrates ratchets');
function reject(mutator, label) {
  const p = serializeProject({ appState, tracks, fx, patterns, ratchets: ratchetBanks });
  mutator(p);
  const result = parseProjectImport(p);
  assert.strictEqual(result.ok, false, label);
  assert(result.errors.some(e => /ratchets|dangerous key/i.test(e)), result.errors.join('; '));
}
reject(p => { p.ratchets = p.ratchets.slice(0, 3); }, 'short banks');
reject(p => { p.ratchets[0].rim = Array(16).fill(1); }, 'unknown track');
reject(p => { delete p.ratchets[0].ether; }, 'missing track');
reject(p => { p.ratchets[0].kick = p.ratchets[0].kick.slice(0, 15); }, 'short steps');
[0, 4, 2.5, '2'].forEach(bad => reject(p => { p.ratchets[0].kick[0] = bad; }, `bad ${bad}`));
const dangerous = JSON.stringify(serializeProject({ appState, tracks, fx, patterns, ratchets: ratchetBanks })).replace('"kick"', '"__proto__":{"polluted":true},"kick"');
const dangerousResult = parseProjectImport(dangerous);
assert.strictEqual(dangerousResult.ok, false, 'dangerous nested ratchet key rejects');
assert.strictEqual({}.polluted, undefined);

const js = fs.readFileSync(path.join(root, 'src', 'main.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles', 'main.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
assert(/const\s+RATCHETS\s*=\s*State\.createRatchetBanks\(\)/.test(js));
assert(/function\s+ratchetOffsets\s*\(\s*stepDuration\s*,\s*count\s*\)/.test(js));
assert(/function\s+scheduledHitTimes\s*\(\s*stepStart\s*,\s*stepDuration\s*,\s*count\s*\)/.test(js));
assert(/Groove\.scheduledHitTimes\(\{[\s\S]*stepIndex:\s*step[\s\S]*ratchets:\s*count[\s\S]*\}\)/.test(js), 'runtime schedules ratchets through the groove timing helper');
assert(/fire\(ti,\s*hitT\)/.test(js));
assert(/getRatchetCount\(RATCHETS\[S\.patt\],\s*tr\.id,\s*step\)/.test(js));
assert(/addEventListener\(['"]contextmenu['"]/.test(js));
assert(/addEventListener\(['"]contextmenu['"],\s*e\s*=>\s*{[\s\S]*?e\.preventDefault\(\);[\s\S]*?if\s*\(\s*longPressFired\s*\)\s*return;[\s\S]*?cycleCellRatchet\(\);[\s\S]*?}\)/.test(js), 'contextmenu suppresses duplicate cycle after pointer long-press');
assert(/pointerdown/.test(js) && /LONG_PRESS_MS/.test(js));
assert(/cycleRatchetCount/.test(js));
assert(/classList\.add\('r'\s*\+\s*(?:nextRatchet|ratchet)/.test(js));
assert(/LONG PRESS STEP = 2x\/3x/.test(html) || /LONG PRESS STEP = 2x\/3x/.test(js) || /HOLD=2x\/3x/.test(html));
assert(/\.sc\.r2/.test(css) && /\.sc\.r3/.test(css));
assert(/ratchets:\s*RATCHETS/.test(js));
assert(/State\.cloneRatchetGrid\(d\.ratchets\[i\]\)/.test(js));
assert(/RATCHETS\[S\.patt\]\s*=\s*State\.createDefaultRatchetGrid\(\)/.test(js));
console.log('Issue 004 ratchet checks passed.');
